---
# - name: Remove old backup file
#   file: 
#     path: /etc/hosts.bkp
#     state: absent
#   ignore_errors: true

- name: Copy "/etc/hosts" file to nodes
  ansible.builtin.copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
