---
- name: Check whether "/swapfile" exists
  register: swap_file
  stat:
    path: /swapfile

- name: Check whether swap config exists
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"
    state: present
  check_mode: yes # This will simulate the task without making changes
  register: swap_config

- name: Allocate the swap file
  when: not swap_file.stat.exists
  shell: fallocate -l {{ swap_vars.size }} /swapfile

- name: Change permission of the swap file
  when: not swap_file.stat.exists
  file:
    path: /swapfile
    mode: 600

- name: Create a swap area on the swap file
  when: not swap_file.stat.exists
  shell: mkswap /swapfile

- name: Activate the swap file as a swap memory
  when: not swap_file.stat.exists
  shell: swapon /swapfile

- name: Append configuration in /etc/fstab
  when: (swap_config.changed) and (swap_file)
  shell: echo "\n/swapfile swap swap defaults 0 0\n" >> /etc/fstab

- name: Set swappiness level
  when: not swap_file.stat.exists
  shell: sysctl vm.swappiness={{ swap_vars.swappiness }}

- name: Append configuration in /etc/sysctl.conf for swappiness
  when: not swap_file.stat.exists
  shell: echo "\nvm.swappiness={{ swap_vars.swappiness }}\n" >> /etc/sysctl.conf
