---
- name: Installing MySQL Server, Router and Dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-router
    - python3-pymysql
  become: true

- name: Installing MySQL Shell
  apt:
    deb: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell_8.4.1-1ubuntu22.04_amd64.deb

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Execute qurries for creating and altering user and privileges 
  community.mysql.mysql_query:
    login_user: "{{ db.user }}"
    login_password: ""
    login_unix_socket: /run/mysqld/mysqld.sock
    query:
      - "ALTER USER '{{ db.user }}'@'localhost' IDENTIFIED WITH caching_sha2_password BY '{{ db.pass }}';"
      - "CREATE USER '{{ db.user }}'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ db.pass }}';"
      - "GRANT ALL PRIVILEGES ON *.* TO '{{ db.user }}'@'%';"
      - "FLUSH PRIVILEGES;"
  ignore_errors: true

- name: Execute qurries required for InnoDB Clustering
  community.mysql.mysql_query:
    login_user: "{{ db.user }}"
    login_password: "{{ db.pass }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    query:
      - "GRANT CLONE_ADMIN, CONNECTION_ADMIN, CREATE USER, EXECUTE, FILE, GROUP_REPLICATION_ADMIN, PERSIST_RO_VARIABLES_ADMIN, PROCESS, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, REPLICATION_APPLIER, REPLICATION_SLAVE_ADMIN, ROLE_ADMIN, SELECT, SHUTDOWN, SYSTEM_VARIABLES_ADMIN ON *.* TO '{{ db.user }}'@'%' WITH GRANT OPTION;"
      - "GRANT DELETE, INSERT, UPDATE ON mysql.* TO '{{ db.user }}'@'%' WITH GRANT OPTION;"
      - "GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER, UPDATE ON mysql_innodb_cluster_metadata.* TO '{{ db.user }}'@'%' WITH GRANT OPTION;"
      - "GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER, UPDATE ON mysql_innodb_cluster_metadata_bkp.* TO '{{ db.user }}'@'%' WITH GRANT OPTION;"
      - "GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER, UPDATE ON mysql_innodb_cluster_metadata_previous.* TO '{{ db.user }}'@'%' WITH GRANT OPTION;"
      - "FLUSH PRIVILEGES;"
  ignore_errors: true

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address = 0.0.0.0"
    backup: yes
  notify:
    - "restart mysql"
    