---
- name: Copy "/etc/hosts" file to node
  include_tasks: tasks/copy_hosts.yml

- name: Make swap and configure swappiness
  include_tasks: tasks/create_swap.yml

- name: Update and Upgrade
  include_tasks: tasks/update_upgrade.yml

- name: Install and configure mysql-server, mysql-shell and mysql-router
  include_tasks: tasks/install_mysql.yml
